use bitflags::bitflags;
use smallvec::SmallVec;
use std::cell::RefCell;
use std::fmt::{self, Debug, Display, Formatter};
use std::hash::{Hash, Hasher};
use std::rc::Rc;

use crate::parser::{LiteralValue, Operator, StString};

mod message;
pub use message::*;

mod types;
pub use types::*;

mod visitor;
pub use visitor::{AstVisitor, AstVisitorMut, DeclVisitor};

mod function_declaration;
pub use function_declaration::FunctionDeclare;

mod expr_statement;
pub use expr_statement::ExprStatement;

mod if_statement;
pub use if_statement::{ElseIfStatement, IfStatement};

mod declaration_statement;
pub use declaration_statement::{DeclKind, Declaration};

mod literal_expression;
pub use literal_expression::LiteralExpression;

mod operator_expression;
pub use operator_expression::OperatorExpression;

mod variable;
pub use variable::{Variable, VariableDeclareGroup};

mod assign_expression;
pub use assign_expression::{AssignExpression, AssignType};

mod compo_access_expression;
pub use compo_access_expression::CompoAccessExpression;

mod statement;
pub use statement::{Statement, StmtKind};

mod expression;
pub use expression::{ExprKind, Expression};

mod variable_expression;
pub use variable_expression::VariableExpression;

mod call_expression;
pub use call_expression::CallExpression;

mod global_variable_declaration;
pub use global_variable_declaration::GlobalVariableDeclare;

mod range_expression;
pub use range_expression::RangeExpression;

pub type SmallVec8<T> = SmallVec<[T; 8]>;
pub type SmallVec3<T> = SmallVec<[T; 3]>;

pub trait HasSourcePosition {}

#[macro_export]
macro_rules! impl_ast_display {
    ($ty:ident, $fun:ident) => {
        impl std::fmt::Display for $ty {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                let mut buf = vec![];
                let mut stringify = $crate::utils::StringifyVisitor::new(&mut buf);
                stringify.$fun(self);

                write!(f, "{}", String::from_utf8_lossy(&buf))
            }
        }
    };
}

pub trait IntoStatement {
    fn into_statement(self) -> Statement;
}

#[macro_export]
macro_rules! impl_into_statement {
    ($ty:ident, $closure:expr) => {
        impl IntoStatement for $ty {
            fn into_statement(self) -> Statement {
                let f: &dyn Fn(Self) -> Statement = &$closure;
                f(self)
            }
        }
    };
}

// #[macro_export]
// macro_rules! impl_accept {
//     ($ty:ident, $closure:expr) => {
//         impl Accept for $ty {
//             fn accept(&self) {
//                 let f: &dyn Fn(Self) -> Statement = &$closure;
//                 f(self)
//             }
//         }
//     };
// }

pub trait IntoExpression {
    fn into_expression(self) -> Expression;
}

#[macro_export]
macro_rules! impl_into_expression {
    ($ty:ident, $closure:expr) => {
        impl IntoExpression for $ty {
            fn into_expression(self) -> Expression {
                let f: &dyn Fn(Self) -> Expression = &$closure;
                f(self)
            }
        }
    };
}

impl_into_expression!(LiteralValue, |x| Expression::literal(Box::new(
    LiteralExpression::new(x)
)));

#[derive(Clone, Debug)]
pub struct Type {
    inner: Rc<TypeInner>,
}

impl Type {
    pub fn from_class(class: TypeClass) -> Self {
        Self {
            inner: Rc::new(TypeInner { class }),
        }
    }

    pub fn type_class(&self) -> &TypeClass {
        &self.inner.class
    }

    pub fn cast<T>(self) -> T {
        todo!()
    }
}

impl Display for Type {
    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
        write!(f, "{}", *self.inner)
    }
}

impl PartialEq for Type {
    fn eq(&self, other: &Self) -> bool {
        self.inner.as_ref() == other.inner.as_ref()
    }
}

impl Eq for Type {}

#[derive(Debug)]
struct TypeInner {
    class: TypeClass,
}

impl PartialEq for TypeInner {
    fn eq(&self, other: &Self) -> bool {
        self.class == other.class
    }
}

impl Eq for TypeInner {}

impl Display for TypeInner {
    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
        f.write_fmt(format_args!("{:?}", self.class))
    }
}

bitflags! {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
    pub struct CompilePassFlags: u32 {
        const NONE                  = 0b0000_0000_0000_0000;

        // HasError
        const HAS_ERROR             = 0b0001_0000_0000_0001;
        // TypeChecked
        const TYPE_CHECKED          = 0b0000_0000_0000_0010;
    }
}

bitflags! {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
    pub struct FunctionFlags: u32 {
        const NONE                  = 0b0000_0000_0000_0000;

        // This Function generated by compiler
        const COMPILER_GENERATED    = 0b0000_0000_0000_0001;
    }
}

bitflags! {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
    pub struct VariableFlags: u32 {
        const NONE              = 0b0000_0000_0000_0000;

        // Scopes
        const GLOBAL            = 0b0000_0000_0000_0001;
        const INPUT             = 0b0000_0000_0000_0010;
        const INOUT             = 0b0000_0000_0000_0100;
        const OUTPUT            = 0b0000_0000_0000_1000;
        const TEMP              = 0b0000_0000_0001_0000;
        const STATIC            = 0b0000_0000_0010_0000;

        // Retain
        const RETAIN            = 0b0000_0001_0000_0000;
        const PERSISTENT        = 0b0000_0010_0000_0000;
        const RETAINPERSISTENT  = Self::RETAIN.bits() | Self::PERSISTENT.bits();

        // CV
        const CONST             = 0b0000_1000_0000_0000;

        // special field
        const ENUM_FIELD        = 0b0001_0000_0000_0000;
        const UNION_FIELD       = 0b0010_0000_0000_0000;
    }
}

impl Display for VariableFlags {
    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
        write!(f, "VAR")?;

        // scope
        if self.contains(Self::GLOBAL) {
            write!(f, "_GLOBAL")?;
        } else if self.contains(Self::INPUT) {
            write!(f, "_INPUT")?;
        } else if self.contains(Self::OUTPUT) {
            write!(f, "_OUTPUT")?;
        } else if self.contains(Self::INOUT) {
            write!(f, "_INOUT")?;
        } else if self.contains(Self::TEMP) {
            write!(f, "_TEMP")?;
        } else if self.contains(Self::STATIC) {
            write!(f, "_STAT")?;
        }

        if self.contains(Self::RETAIN) {
            write!(f, " RETAIN")?;
        }

        if self.contains(Self::PERSISTENT) {
            write!(f, " PERSISTENT")?;
        }

        Ok(())
    }
}

bitflags! {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
    pub struct CompilerInternalFlags: u32 {
        const NONE              = 0b0000_0000_0000_0000;
        const HAS_ERROR         = 0b0000_0000_0000_0001;
    }
}

#[derive(Debug)]
pub enum DeclareClass {
    Function,
    Program,
    FunctionBlock,
    Method,
    Action,
}

#[derive(Debug, Clone, Eq, PartialEq)]
pub enum UserTypeClass {
    Alias,
    Enum,
    Struct,
    Union,
}

#[derive(Debug, Eq, PartialEq, Clone)]
pub enum TypeClass {
    /// 'BIT', one bit type
    Bit,
    /// 'BOOL', boolean type
    Bool,
    /// 'SINT', 8 bits signed
    SInt,
    /// 'BYTE', 8 bits unsigned
    Byte,
    /// 'INT', 16 bits signed
    Int,
    /// 'UINT', 16 bits unsigned
    UInt,
    /// 'DINT', 32 bits signed
    DInt,
    /// 'UDINT' 32 bits unsigned
    UDInt,
    /// 'LINT', 64 bits signed
    LInt,
    /// 'ULINT', 64 bits unsigned
    ULInt,
    /// 'REAL', 32 bits float
    Real,
    /// 'LREAL' 64 bits float
    LReal,
    /// 'STRING' string type
    String,
    /// UserType
    UserType(RefCell<UserType>),
    /// ArrayType
    Array(RefCell<ArrayType>),
}

impl Hash for TypeClass {
    fn hash<H: Hasher>(&self, state: &mut H) {
        let tag = match self {
            TypeClass::Bit => 1,
            TypeClass::Bool => 2,
            TypeClass::Byte => 3,
            TypeClass::UInt => 4,
            TypeClass::Int => 5,
            _ => unimplemented!("{:?}", self),
        };

        tag.hash(state);

        // TODO: incomplete implements
        match self {
            TypeClass::UserType(user_type) => {
                user_type.borrow().name().hash(state);
            }
            TypeClass::Array(array_type) => {
                let array_type = array_type.borrow();
                let base_type = array_type.base_type().borrow();
                base_type.type_class().hash(state);
            }
            _ => {}
        }
    }
}

impl Display for TypeClass {
    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
        match self {
            TypeClass::Bit => write!(f, "BIT"),
            TypeClass::Bool => write!(f, "BOOL"),
            TypeClass::SInt => write!(f, "SINT"),
            TypeClass::Byte => write!(f, "BYTE"),
            TypeClass::Int => write!(f, "INT"),
            TypeClass::UInt => write!(f, "UINT"),
            TypeClass::DInt => write!(f, "DINT"),
            TypeClass::UDInt => write!(f, "UDINT"),
            TypeClass::LInt => write!(f, "LINT"),
            TypeClass::ULInt => write!(f, "ULINT",),
            TypeClass::Real => write!(f, "REAL"),
            TypeClass::LReal => write!(f, "LREAL"),
            TypeClass::String => write!(f, "STRING"),
            TypeClass::UserType(u) => write!(f, "{}", u.borrow()),
            TypeClass::Array(arr) => write!(f, "{}", arr.borrow()),
        }
    }
}
