name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: ConorMacBride/install-package@v1
      with:
        apt: liblua5.4-dev lua5.4 libtinfo5

    - uses: KyleMayes/install-llvm-action@v2
      with:
        version: "18"
        directory: ${{ runner.temp }}/llvm-18

    - uses: actions/checkout@v3

    - name: Build
      run: cargo build --verbose
      env:
        LLVM_SYS_180_PREFIX: ${{ runner.temp }}/llvm-18
    - name: Run tests
      run: |
        cargo test --verbose
      env:
        LLVM_SYS_180_PREFIX: ${{ runner.temp }}/llvm-18
    - name: Run tests with default parser
      run: |
        cargo test --verbose --no-default-features --package stc-rs
      env:
        LLVM_SYS_180_PREFIX: ${{ runner.temp }}/llvm-18
