name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: ConorMacBride/install-package@v1
      with:
        apt: libpango1.0-dev libgtk-4-dev

    - uses: KyleMayes/install-llvm-action@v1
      with:
        version: "16.0"
        directory: ${{ runner.temp }}/llvm-16

    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
      env:
        LLVM_SYS_160_PREFIX: ${{ runner.temp }}/llvm-16
    - name: Run tests
      run: cargo test --verbose
      env:
        LLVM_SYS_160_PREFIX: ${{ runner.temp }}/llvm-16
